language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t aarontheape/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true aarontheape/docker-react npm run test

